# Use the official Python image as the base image
FROM python:3.8-bullseye

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt /app/

# Install any needed packages specified in requirements.txt
RUN apt-get update && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . /app/

# Expose port 5000 for the Flask app
EXPOSE 5000

# Define environment variable
ENV FLASK_APP=your_app_file_name.py

# Run app.py when the container launches
CMD ["flask", "run", "--host=0.0.0.0"]
