version: 2.1

jobs:
  say-hello:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            apt-get update
     - run:
          name: "Update Python Packages"
          command: "pip install pytest"    
      - run:
          name: "Update Python Packages"
          command: "pip install flask"  
      - run:
          name: "Update Python Packages"
          command: "pip install snowflake-connector-python==2.6.2"

      - run:
          name: "Run pytest"
          command: "pytest test.py"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
