version: 2.1

jobs:
  say-hello:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y python3 libssl-dev
            pip install pytest snowflake-connector-python flask
      - run:
          name: "Run pytest"
          command: "pytest test.py"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
