# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: python:3.8  # Use an official Python image with Python 3.8
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: Install Python
          command: |
            apt-get update
            apt-get install -y python3
      - run:
          name: "Install pytest"
          command: "pip install pytest"
      - run:
          name: "Install snowflake"
          command: "pip install snowflake-connector-python"
      - run:
          name: "Install flask"
          command: "pip install flask" 
      - run:
          name: Install Dependencies
          command: apt-get update && apt-get install -y libssl-dev

      - run:
          name: "Run pytest"
          command: "pytest test.py"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
