version: 2.1

jobs:
  say-hello:
    docker:
      - image: debian:bookworm-slim  # Use Debian Bookworm as the base image
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            apt-get update
            apt-get install -y python3-pip libssl3=3.0.9-1
            pip install pytest snowflake-connector-python==3.2.0 flask
            pip install oscrypto==1.3.0
      - run:
          name: "Run pytest"
          command: "pytest test.py"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
