version: 2.1

jobs:
  say-hello:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            apt-get update
            apt-get install -y libssl-dev  # Install libssl-dev (which provides libcrypto)
            pip install pytest flask
            pip install snowflake-connector-python==2.6.2  # Specify the version you need
      - run:
          name: "Run pytest"
          command: "pytest test.py"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
