version: 2.1

jobs:
  say-hello:
    docker:
      - image: python:3.8-bullseye  # Use the official Python image based on Debian Bullseye
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            apt-get update
            pip install pytest snowflake-connector-python==3.2.0 flask
            pip install oscrypto==1.3.0
      - run:
          name: "Run pytest"
          command: "pytest test.py"

  start-flask-backend:
    steps:
      - checkout
      - run:
          name: Start Flask Backend
          command: |
            python app.py &
            sleep 5 # Waits for the Flask server to start
            xdg-open http://127.0.0.1:5000

workflows:
  build-test-and-deploy:
    jobs:
      - say-hello
      - start-flask-backend:
          branches:
            only:
              - main
