version: 2.1

jobs:
  build-and-test:
    docker:
      - image: python:3.8-bullseye
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            apt-get update
            pip install pytest snowflake-connector-python==3.2.0 flask
            pip install oscrypto==1.3.0
      - run:
          name: "Run pytest"
          command: "pytest test.py"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-and-test
