version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies and Run Tests
          command: |
            apt-get update
            pip install pytest snowflake-connector-python==3.2.0 flask oscrypto==1.3.0
            python3 app.py

  build_and_push:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Install Docker client
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-ce-cli
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/myapp:${CIRCLE_SHA1} .
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push $DOCKERHUB_USERNAME/myapp:${CIRCLE_SHA1}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test:
          filters:
            branches:
              only: main
      - build_and_push:
          filters:
            branches:
              only: main  # Specify the branch you want to trigger the deployment
