version: 2.1

jobs:
  build-and-test:
    docker:
      - image: python:3.8-bullseye
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            apt-get update
            pip install pytest snowflake-connector-python==3.2.0 flask
            pip install oscrypto==1.3.0
      - run:
          name: "Run pytest"
          command: "pytest test.py"

  build-and-push:
    docker:
      - image: docker:19.03.13
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: "Build and Push Docker Image"
          command: |
            docker build --no-cache -t prathibha07/projectimage1:latest .
            echo $DOCKERHUB_PASSWORD | docker login --username prathibha07 --password-stdin
            docker push prathibha07/projectimage1:latest

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-and-test
      - build-and-push:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
