version: 2.1

jobs:
  say-hello:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            apt-get update
            apt-get install -y libssl-dev  # Install libssl-dev (which provides libcrypto)
            pip install pytest snowflake-connector-python flask
      - run:
          name: "Install Cryptographic Libraries (with Debugging)"
          command: |
            apt-get update
            apt-get install -y libssl-dev
            echo "Installed libssl-dev successfully"
- run:
          name: "Install Cryptographic Libraries"
          command: "apt-get install -y libssl-dev"
      - run:
          name: "Update Python Packages"
          command: "pip install --upgrade oscrypto snowflake-connector-python"
      - run:
          name: "Run pytest"
          command: "pytest test.py"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
