version: 2.1

jobs:
  start-flask-backend:
    steps:
      - checkout
      - run:
          name: Start Flask Backend
          command: |
            python app.py &
            sleep 5 # Waits for the Flask server to start
            xdg-open http://127.0.0.1:5000

workflows:
  build-test-and-deploy:
    jobs:
      - start-flask-backend

