version: 2.1

jobs:
  say-hello:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            apt-get update
            pip3 install pytest snowflake-connector-python==3.2.0 flask
            pip3 install oscrypto==1.3.0
      - run:
          name: "Run pytest"
          command: "pytest test.py"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
