version: 2.1

jobs:
  say-hello:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install OpenSSL 3.0.9
          command: |
            apt-get update
            apt-get install -y libssl-dev  # Install OpenSSL development library
            wget https://www.openssl.org/source/openssl-3.0.9.tar.gz
            tar -xzvf openssl-3.0.9.tar.gz
            cd openssl-3.0.9
            ./config
            make
            make install
      - run:
          name: Install Dependencies
          command: |
            pip3 install pytest snowflake-connector-python==3.2.0 flask
            pip3 install oscrypto==1.3.0
      - run:
          name: Run pytest
          command: "pytest test.py"

workflows:
  version: 2
  say-hello-workflow:
    jobs:
      - say-hello
