version: 2.1

jobs:
  say-hello:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Update Package Lists
          command: |
            apt-get update
            apt-get install -y libssl-dev  # Install OpenSSL development library
      - run:
          name: Install Dependencies
          command: |
            pip3 install pytest snowflake-connector-python==3.2.0 flask
            pip3 install oscrypto==1.3.0
      - run:
          name: Run pytest
          command: "pytest test.py"

workflows:
  version: 2
  say-hello-workflow:
    jobs:
      - say-hello
