version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            pip install pytest numpy
      - run:
          name: "Run tests"
          command: "pytest test_sparse_recommender.py"
      

  build-and-push-image:
    docker:
      - image: docker:20.10.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t josnapitta/test_sparse_recommender:v1 .

      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "pitta1234" | docker login -u "josnapitta" --password-stdin
            docker push josnapitta/test_sparse_recommender:v1

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build-and-test
      - build-and-push-image:
          requires:
            - build-and-test
